openapi: 3.0.3 # version of the specification 
info: 
  version: '0.0.1' 
  title: Sign PDF with QTSP

paths: 
  /sign-pdf: 
    post: 
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file_to_be_signed:
                  type: string
                  format: binary
              
      summary: Return a PDF signed by QTSP 
      operationId: signPdf 
      responses: 
        200:
          description: Success sign
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/signResponse' 
        400:
          description: Bad client request
        500:
          description: Internal server error

  /download/{filename}: 
    get: 
      parameters:
      - name: filename
        in: path
        description: File name
        required: true
        schema:
          type: string
          format: filename
      summary: Returns the requested file
      operationId: downloadPdf 
      responses: 
        200:
          description: Success download
          content: 
            application/pdf:
              schema:
                type: string
                format: binary
        404:
          description: File not found


components: 
  schemas: 
    signResponse: 
      type: object 
      properties: 
        hash: 
          type: string 
          example: 'Base 64 file hash' 
        signed-hash: 
          type: string 
          example: 'Base 64 signed hash' 
        signed-file-url: 
          type: string 
          example: 'URL to download signed file' 
        signed: 
          type: boolean
          example: True 

servers:
  - url: https://io-sign-qtsp.azurewebsites.net
    variables: {}